### ISSUE TITLE
在popback中调用的问题

### ISSUE THREAD

**Issue by duanhjlt** [VictorZhang2014/ZRAlertController#1]
如果放在一个VC的[self.navigationController popViewControllerAnimated:YES];之前调用会有问题：

1. ios8以上的实现无法返回到上一个页面；
2. ios8以下的实现，如果当前vc中吊起了键盘，返回后键盘会闪现以下。

**Comment by VictorZhang2014** [comment]
已修复！使用时，如果点击“确定”按钮后，在block里执行事件

**Comment by duanhjlt** [comment]
赞一个
